NAME = alutest
SRCS = build/alu_test.c
include $(AM_HOME)/Makefile

# GENERATOR = build/gen_alu_test

# $(GENERATOR): gen_alu_test.c
# 	echo "gcc -O2 -Wall -Werror $^ -o $@"
# 	gcc -O2 -Werror $^ -o $@

# $(SRCS): $(GENERATOR)
# 	$^ > $@
